services:
  app:
    build: .
    container_name: python_dev_app
    ports:
      - "8888:8888"   # Jupyter Lab
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://myuser:mypassword@db:5432/omni-db
      - PREFECT_API_URL=http://prefect-server:4200/api
    depends_on:
      - db
      - prefect-server

  prefect-server:
    image: prefecthq/prefect:3-latest
    container_name: prefect_server
    command: prefect server start --host 0.0.0.0
    ports:
      - "127.0.0.1:4200:4200"
    environment:
      - PREFECT_SERVER_API_HOST=0.0.0.0
      - PREFECT_UI_API_URL=http://localhost:4200/api

  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: omni-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: cloudbeaver
    restart: unless-stopped
    ports:
      - "8978:8978"   # CloudBeaver Web UI
    volumes:
      - cloudbeaver_data:/opt/cloudbeaver/workspace
    depends_on:
      - db

  metabase:
    image: metabase/metabase:latest
    container_name: metabase_app
    restart: unless-stopped
    ports:
      - "3000:3000"   # Metabase Web UI
    environment:
      # ตั้งค่าให้ Metabase เก็บข้อมูลระบบลงใน Postgres 
      - MB_DB_TYPE=postgres
      - MB_DB_HOST=db
      - MB_DB_PORT=5432
      - MB_DB_DBNAME={DB_NAME}
      - MB_DB_USER={DB_USER}
      - MB_DB_PASS={DB_PASSWORD}
      - JAVA_OPTS=-Xmx512m
    depends_on:
      - db

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-server
    restart: always
    environment:
      - CLICKHOUSE_DB={DB_NAME}
      - CLICKHOUSE_USER={DB_USER}
      - CLICKHOUSE_PASSWORD={DB_PASSWORD}
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
      - CLICKHOUSE_DEFAULT_MAX_THREADS=1 
      - CLICKHOUSE_DEFAULT_MAX_MEMORY_USAGE=536870912 # 512MB
    ports:
      - "8123:8123" # HTTP Interface
      - "9000:9000" # Native Client Interface
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_logs:/var/log/clickhouse-server

  vquery_backend:
    image: vquery/backend:latest
    container_name: vquery-service
    pull_policy: never
    command: /bin/sh -c "sleep 9999"
    ports:
      - "6001:6001"
    environment:
      - DB_TYPE=clickhouse
      - DB_HOST=clickhouse
      - DB_PORT=8123
      - DB_NAME={DB_NAME}
      - DB_USER={DB_USER}
      - DB_PASSWORD={DB_PASSWORD}
      - CACHE_ENABLE=false
    depends_on:
      - clickhouse            

  vquery_frontend:
    image: service-vquery-frontend:1
    platform: linux/amd64
    container_name: vquery-frontend
    pull_policy: never
    command: tail -f /dev/null
    ports:
      - "6000:8888"

volumes:
  postgres_data:
  cloudbeaver_data:
  clickhouse_data:
  clickhouse_logs: