version: '3.8'

services:
  app:
    build: .
    container_name: python_dev_app
    ports:
      - "8888:8888"   # Jupyter Lab
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://myuser:mypassword@db:5432/mydb
      - PREFECT_API_URL=http://prefect-server:4200/api
    depends_on:
      - db
      - prefect-server

  prefect-server:
    # ใช้ Official Image Prefect v3 ล่าสุดที่แก้บั๊ก Pydantic v2 แล้ว
    image: prefecthq/prefect:3-latest
    container_name: prefect_server
    command: prefect server start --host 0.0.0.0
    ports:
      - "127.0.0.1:4200:4200"
    environment:
      - PREFECT_SERVER_API_HOST=0.0.0.0
      - PREFECT_UI_API_URL=http://localhost:4200/api

  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: